DOCS: switch to  ammaraskar/sphinx-action

diff --git a/.github/workflows/sphinx_docs_to_gh_pages.yaml b/.github/workflows/sphinx_docs_to_gh_pages.yaml
--- a/.github/workflows/sphinx_docs_to_gh_pages.yaml
+++ b/.github/workflows/sphinx_docs_to_gh_pages.yaml
@@ -2,37 +2,49 @@ name: Sphinx docs to gh-pages
 
 on:
   push:
-    branches:
+    branches:    
       - main
 
-# workflow_dispatch:        # Un comment line if you also want to trigger action manually
-
 jobs:
-  sphinx_docs_to_gh-pages:
+  build:
+
     runs-on: ubuntu-latest
-    name: Sphinx docs to gh-pages
+
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Make conda environment
-        uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: 3.8    # Python version to build the html sphinx documentation
-          environment-file: docs/docs_env.yaml    # Path to the documentation conda environment
-          auto-update-conda: false
-          auto-activate-base: false
-          show-channel-urls: true
-      - name: Installing the library
-        shell: bash -l {0}
-        run: |
-          python setup.py install
-      - name: Running the Sphinx to gh-pages Action
-        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
-        with:
-          branch: main
-          dir_docs: docs
-          # No API doc in this repo
-          # sphinxapiopts: '--separate -o . ../'
-          # sphinxapiexclude: '../*setup* ../*.ipynb'
-          sphinxopts: ''
+    - uses: actions/checkout@v1
+    # Example of using a custom build-command.
+    # this commit SHA corresponds to tag `0.4`
+    - uses: C2SM/sphinx-action@sphinx-latest
+      with:
+        build-command: "sphinx-build -b html . _build"
+        docs-folder: "docs/"
+    # Great extra actions to compose with:
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: DocumentationHTML
+        path: docs/_build/
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      # this commit SHA corresponds to tag `v0.6.0`
+      uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
+      with:
+        force: true
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
+
